name: arrayloader-benchmarks
channels:
  - nvidia
  - rapidsai
  - numba
  - conda-forge
  - pytorch
dependencies:
  - python=3.11.8
  - cudatoolkit==11.4.1
  - h5py
  - loguru
  - merlin-core
  - merlin-dataloader
  - notebook
  - numpy
  - pandas
  - pip
  - polars
  - pyarrow
  - pytorch>=2,<2.2
  - rich
  - s3fs
  - scanpy
  - zarr
  - tensorstore
  - pip:
      - -r requirements.txt
