name: arrayloader-benchmarks
channels:
  - nvidia
  - rapidsai
  - numba
  - conda-forge
  - pytorch
dependencies:
  - python=3.11.8
  - boto3==1.34.51
  - cudatoolkit==11.7.0
  - dask[dataframe]==2023.9.2
  - distributed==2023.9.2
  - fsspec==2024.3.1
  - h5py
  - loguru
  - merlin-core==23.08.00
  - merlin-dataloader==23.08.00
  - mkl<2024  # https://github.com/pytorch/pytorch/issues/123097#issuecomment-2055236551
  - notebook
  - numpy
  - pandas
  - pip
  - polars
  - pyarrow==15.0.2
  - pytorch==2.0.1[build=py3.11_cuda11*]
  - rich
  - s3fs==2024.3.1
  - scanpy
  - tensorstore==0.1.56
  - torchdata==0.7.1
  - zarr
