name: lamin
channels:
  - nvidia
  - rapidsai
  - numba
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - h5py
  - loguru
  - merlin-core
  - merlin-dataloader
  - notebook
  - numpy
  - pandas
  - pip
  - polars
  - pyarrow
  - pytorch
  - rich
  - s3fs
  - scanpy
  - torchdata
  - zarr
  - tensorstore
  - pip:
      - bionty
      - bokeh
      - dask[dataframe]
      - distributed
      - plotly
      - rich-click
      - tiledbsoma==1.7.2
